### ISSUE TITLE
Plan: Can Users Pin own repos? Yes can users view or pin others? view: Yes, pin: No.

### ISSUE THREAD

**Issue by ohboyd** [MichaelDimmitt/gitorganize-FE#4]
Seeing if only the repo creator can pin, or if any Joe-schmo can.

**Comment by ohboyd** [comment]
Doesn't look like I can pin anything, so that means that this is likely a nice feature. It will keep people from reporting the same problems again and again, since they'll see "ah you actually know about this issue and are trying to fix it or have a workaround"

**Comment by MichaelDimmitt** [comment]
Plan: Anyone can view a profile
but only a single user can update their profile.

information sourced from this comment 👍 . Stay tuned!
https://github.com/MichaelDimmitt/gitorganize-FE/issues/2#issuecomment-447584289
